default_install_hook_types: [pre-commit, pre-push]

repos:
  - repo: local
    hooks:
      - id: ruff-check
        name: ruff check
        entry: uv run --extra dev ruff check --fix
        language: system
        types_or: [python, pyi]
        stages: [pre-commit]

      - id: ruff-format
        name: ruff format
        entry: uv run --extra dev ruff format
        language: system
        types_or: [python, pyi]
        stages: [pre-commit]

      - id: check-toml
        name: check TOML
        entry: uv run --extra dev check-toml
        language: system
        types: [toml]
        stages: [pre-commit]

      - id: check-yaml
        name: check YAML
        entry: uv run --extra dev check-yaml
        language: system
        types: [yaml]
        stages: [pre-commit]

      - id: check-merge-conflict
        name: check merge conflicts
        entry: uv run --extra dev check-merge-conflict
        language: system
        types: [text]
        stages: [pre-commit]

      - id: check-added-large-files
        name: check added large files
        entry: uv run --extra dev check-added-large-files
        language: system
        stages: [pre-commit]

      - id: end-of-file-fixer
        name: fix end of files
        entry: uv run --extra dev end-of-file-fixer
        language: system
        types: [text]
        stages: [pre-commit]

      - id: trailing-whitespace
        name: trim trailing whitespace
        entry: uv run --extra dev trailing-whitespace-fixer
        language: system
        types: [text]
        stages: [pre-commit]

      - id: pytest
        name: pytest
        entry: uv run --extra dev pytest
        language: system
        pass_filenames: false
        stages: [pre-push]
